# Generated by Django 4.1.3 on 2022-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
