# Generated by Django 4.1.3 on 2022-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_alter_daily_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='img',
            field=models.ImageField(upload_to='files'),
        ),
    ]
