# Generated by Django 4.1.3 on 2022-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_daily_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
